<?php
/** @var $messageViewModel Macademy\JsFun\ViewModel\Message */
$messageViewModel = $block->getData('message_view_model');
?>

<div id="vue-test">
    <h1>{{ message }}</h1>
</div>

<script type="text/x-magento-init">
    {
        "#vue-test": {
            "Macademy_JsFun/js/vue-test": {
                "message": "<?= $messageViewModel->getMessage(); ?>"
            }
        }
    }
</script>